version: '3.8'

services:
  cassandra:
    image: cassandra:latest
    container_name: cassandra-for-hands-on
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_DC=dc1
      - CASSANDRA_RACK=rack1
      - CASSANDRA_ENDPOINT_SNITCH=GossipingPropertyFileSnitch
    volumes:
      - cassandra_data:/var/lib/cassandra
    healthcheck:
        test: ["CMD", "cqlsh", "-e", "describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10

volumes:
  cassandra_data:
